2024--1C-Estacionamiento/2024--1C-Estacionamiento/Models/Persona.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using _2024__1C_Estacionamiento.Helpers;
using Microsoft.AspNetCore.Identity;



namespace _2024__1C_Estacionamiento.Models
{
    public class Persona : IdentityUser<int>
    {
        public Persona()
        {

        }
        //Comento Id porque ya lo tiene IdentityUser
        //public int Id { get; set; }

        [Required(ErrorMessage =ErrorMsge.Requerido)]
        [StringLength(100, MinimumLength=2, ErrorMessage = ErrorMsge.Longitud)]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage = "Solo se permiten letras")]
        public string Nombre { get; set; }


        [Required(ErrorMessage = ErrorMsge.Requerido)]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "La cantidad de Caracteres es invalida")]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage = "Solo se permiten letras")]
        public string Apellido { get; set; }

        [Required(ErrorMessage = ErrorMsge.Requerido)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Solo se permiten numeros")]
        [Display(Name = Alias.DNI)]

     
        public string Dni { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = Alias.Email)]
        //public string Email { get; set; }

        public string NombreCompleto
        {
            get
            {
                return $"{Nombre}, {Apellido}";
            }
           
        }

        //Adecuacion de identityUser
        public override string Email
        {
            get { return base.Email; }
            set { base.Email = value; }
        }

        public Direccion Direccion { get; set; }

        public List<Telefono> Telefonos { get; set; }

    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Controllers/PersonaController.cs
using _2024__1C_Estacionamiento.Models;
using Microsoft.AspNetCore.Mvc;

namespace _2024__1C_Estacionamiento.Controllers
{
    public class PersonaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //Creo Persona con Get
        public ActionResult CreateGet()   //Ejemplo Con Get
        {


            return View();

        }
        //Creo Persona con Post
        public ActionResult CreatePost() //Ejemplo con Post
        {


            return View();

        }
        //Creo persona con query string
        public IActionResult CrearPersona(string nombre, string apellido, string dni, string email)
        {
            Persona persona = new Persona()

            {
                Apellido = apellido,
                Dni = dni,
                Nombre = nombre,
                Email = email
            };

            return View(persona);

        }
    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2024__1C_Estacionamiento.Data;
using _2024__1C_Estacionamiento.Models;

namespace _2024__1C_Estacionamiento.Controllers
{
    public class PersonasController : Controller
    {
        private readonly EstacionamientoContext _context;

        public PersonasController(EstacionamientoContext context)
        {
            _context = context;
        }

        // GET: Personas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Personas.ToListAsync());
        }

        // GET: Personas/Details/5

        //Aca va el include de direccion y telefonos para que muestre el detalle de la persona con su direccion y telefonos
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas.Include(clt => clt.Telefonos)
                                        .Include(clt => clt.Direccion)
                                        .FirstOrDefaultAsync(m => m.Id == id);
            //Incluyo los objetos del contexto


            if (persona == null)
            {
                return NotFound();
            }
            var direccion = await _context.Direccion
                .FirstOrDefaultAsync(m => m.Id == id);

            //if (direccion == null)
            //{
            //    return NotFound();
            //}
          

            persona.Direccion = direccion;  
            //Mando al la persona con la direccion y el telefono para que se muestre en la vista
            return View(persona);


        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Dni,Email")] Persona persona)
        {
            if (ModelState.IsValid)
            {//Agrego el modelo Personas para ser mas claro, aunque no viene por default en scaffoldin es mas claro
             //para que se guarde en la base de datos
                _context.Personas.Add(persona);
                await _context.SaveChangesAsync();
                }
            //Redirecicono al create de Direccion para agregarle una direccion
                return RedirectToAction("Create", "Direcciones", new { id = persona.Id });



            }
           
        

        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas.FindAsync(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Email,Dni")] Persona persona)
        {

            if (id != persona.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try

                {
                    //Voy a buscar la persona en la base de datos y si existe hago el update de los datos que quiero. por ejemplo 
                    // si no quiero que se pueda modificar el email, no lo pongo en el bind
                    var personaDb = _context.Personas.Find(persona.Id);
                    if (personaDb != null)
                    {
                        personaDb.Nombre = persona.Nombre;
                        personaDb.Apellido = persona.Apellido;
                        personaDb.Dni = persona.Dni;
                        _context.Personas.Update(personaDb);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        return NotFound();
                    }


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var persona = await _context.Personas.FindAsync(id);
            if (persona != null)
            {
                _context.Personas.Remove(persona);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id)
        {
            return _context.Personas.Any(e => e.Id == id);
        }


    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Persona/CrearPersona.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Persona


@if (Model != null)
{
    <h2>Los Datos de la Personas son :</h2>

    <ul>
        <li>
            <p>el nombre completo es @Model.NombreCompleto</p>
        </li>

    </ul>
}
else
{
    <h2>La Persona es Nula</h2>
}
<div>
    <h2>Los Datos de la Personas son :</h2>

    <ul>
        <li>
            <p>el nombre completo es @Model.NombreCompleto</p>
        </li>

    </ul>

</div>

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Persona/CreateGet.cshtml
@model Persona

@{
    ViewData["Title"] = "Crear Persona Con Formulario Get";
}



<h4>Persona GET SiAparece en el Query String</h4>


<form method="get" action="@Url.Action("CrearPersona", "Persona")">
    <div class="form-group" >
        <label for="Nombre">Ingrese su nombre</label>
        <input type="text" id="Nombre" name="Nombre" class="form-control" />
        <label for="Apellido">Ingrese su Apellido</label>
        <input type="text" id="Apellido" name="Apellido" class="form-control" />

    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Persona/CreatePost.cshtml
@model Persona

@{
    ViewData["Title"] = "Crear Persona Con Formulario Post";
}



<h4>Persona POST No Aparece en el Query String</h4>


<form action="@Url.Action("CrearPersona", "Persona")" method="post">
    <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" required>
    </div>
    <div class="form-group">
        <label for="apellido">Apellido</label>
        <input type="text" class="form-control" id="apellido" name="apellido" required>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Persona/Index.cshtml
@model List<Persona>


<h2>Estas son las Personas creadas Con nuestra webApp</h2>

@if (Model != null)
{
    foreach (Persona persona in Model)
    {
        <p>@persona.NombreCompleto</p>
    }
}
else
{
    <p>No hay personas creadas</p>
}
<div>
    <a asp-controller="Persona" asp-action="CrearPersona">Crear una persona</a>
</div>

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Persona/RepoPersonas.cshtml
@model List<Persona>

<p>Las Personas en la lista son</p>

<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th>
                Nombre
            </th>

            <th>
                Apellido
            </th>
        </tr>
    </thead>



    <tbody>
        @foreach (Persona persona in Model)
        {
            <tr>
                <td> @persona.Nombre</td>
                <td> @persona.Apellido</td>
            </tr>

        }

    </tbody>
</table>