2024--1C-Estacionamiento/2024--1C-Estacionamiento/Models/Persona.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using _2024__1C_Estacionamiento.Helpers;
using Microsoft.AspNetCore.Identity;



namespace _2024__1C_Estacionamiento.Models
{
    public class Persona : IdentityUser<int>
    {
        public Persona()
        {

        }
        //Comento Id porque ya lo tiene IdentityUser
        //public int Id { get; set; }

        [Required(ErrorMessage =ErrorMsge.Requerido)]
        [StringLength(100, MinimumLength=2, ErrorMessage = ErrorMsge.Longitud)]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage = "Solo se permiten letras")]
        public string Nombre { get; set; }


        [Required(ErrorMessage = ErrorMsge.Requerido)]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "La cantidad de Caracteres es invalida")]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage = "Solo se permiten letras")]
        public string Apellido { get; set; }

        [Required(ErrorMessage = ErrorMsge.Requerido)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Solo se permiten numeros")]
        [Display(Name = Alias.DNI)]

     
        public string Dni { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = Alias.Email)]
        //public string Email { get; set; }

        public string NombreCompleto
        {
            get
            {
                return $"{Nombre}, {Apellido}";
            }
           
        }

        //Adecuacion de identityUser
        public override string Email
        {
            get { return base.Email; }
            set { base.Email = value; }
        }

        public Direccion Direccion { get; set; }

        public List<Telefono> Telefonos { get; set; }

    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Controllers/PersonaController.cs
using _2024__1C_Estacionamiento.Models;
using Microsoft.AspNetCore.Mvc;

namespace _2024__1C_Estacionamiento.Controllers
{
    public class PersonaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //Creo Persona con Get
        public ActionResult CreateGet()   //Ejemplo Con Get
        {


            return View();

        }
        //Creo Persona con Post
        public ActionResult CreatePost() //Ejemplo con Post
        {


            return View();

        }
        //Creo persona con query string
        public IActionResult CrearPersona(string nombre, string apellido, string dni, string email)
        {
            Persona persona = new Persona()

            {
                Apellido = apellido,
                Dni = dni,
                Nombre = nombre,
                Email = email
            };

            return View(persona);

        }
    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2024__1C_Estacionamiento.Data;
using _2024__1C_Estacionamiento.Models;

namespace _2024__1C_Estacionamiento.Controllers
{
    public class PersonasController : Controller
    {
        private readonly EstacionamientoContext _context;

        public PersonasController(EstacionamientoContext context)
        {
            _context = context;
        }

        // GET: Personas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Personas.ToListAsync());
        }

        // GET: Personas/Details/5

        //Aca va el include de direccion y telefonos para que muestre el detalle de la persona con su direccion y telefonos
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas.Include(clt => clt.Telefonos)
                                        .Include(clt => clt.Direccion)
                                        .FirstOrDefaultAsync(m => m.Id == id);
            //Incluyo los objetos del contexto


            if (persona == null)
            {
                return NotFound();
            }
            var direccion = await _context.Direccion
                .FirstOrDefaultAsync(m => m.Id == id);

            //if (direccion == null)
            //{
            //    return NotFound();
            //}
          

            persona.Direccion = direccion;  
            //Mando al la persona con la direccion y el telefono para que se muestre en la vista
            return View(persona);


        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Dni,Email")] Persona persona)
        {
            if (ModelState.IsValid)
            {//Agrego el modelo Personas para ser mas claro, aunque no viene por default en scaffoldin es mas claro
             //para que se guarde en la base de datos
                _context.Personas.Add(persona);
                await _context.SaveChangesAsync();
                }
            //Redirecicono al create de Direccion para agregarle una direccion
                return RedirectToAction("Create", "Direcciones", new { id = persona.Id });



            }
           
        

        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas.FindAsync(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Email,Dni")] Persona persona)
        {

            if (id != persona.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try

                {
                    //Voy a buscar la persona en la base de datos y si existe hago el update de los datos que quiero. por ejemplo 
                    // si no quiero que se pueda modificar el email, no lo pongo en el bind
                    var personaDb = _context.Personas.Find(persona.Id);
                    if (personaDb != null)
                    {
                        personaDb.Nombre = persona.Nombre;
                        personaDb.Apellido = persona.Apellido;
                        personaDb.Dni = persona.Dni;
                        _context.Personas.Update(personaDb);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        return NotFound();
                    }


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var persona = await _context.Personas.FindAsync(id);
            if (persona != null)
            {
                _context.Personas.Remove(persona);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id)
        {
            return _context.Personas.Any(e => e.Id == id);
        }


    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Controllers/TelefonosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2024__1C_Estacionamiento.Data;
using _2024__1C_Estacionamiento.Models;

namespace _2024__1C_Estacionamiento.Controllers
{
    public class TelefonosController : Controller
    {
        private readonly EstacionamientoContext _context;

        public TelefonosController(EstacionamientoContext context)
        {
            _context = context;
        }

        // GET: Telefonos
        public async Task<IActionResult> Index()
        {
            var estacionamientoContext = _context.Telefono.Include(t => t.Persona);
            return View(await estacionamientoContext.ToListAsync());
        }

        // GET: Telefonos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telefono = await _context.Telefono
                .Include(t => t.Persona)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (telefono == null)
            {
                return NotFound();
            }

            return View(telefono);
        }

        // GET: Telefonos/Create
        public IActionResult Create()
        {
            ViewData["PersonaId"] = new SelectList(_context.Personas, "Id", "Apellido");
            return View();
        }

        // POST: Telefonos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CodArea,Numero,Principal,Tipo,PersonaId")] Telefono telefono)
        {
            if (ModelState.IsValid)
            {
                _context.Add(telefono);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PersonaId"] = new SelectList(_context.Personas, "Id", "Apellido", telefono.PersonaId);
            return View(telefono);
        }

        // GET: Telefonos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telefono = await _context.Telefono.FindAsync(id);
            if (telefono == null)
            {
                return NotFound();
            }
            ViewData["PersonaId"] = new SelectList(_context.Personas, "Id", "Apellido", telefono.PersonaId);
            return View(telefono);
        }

        // POST: Telefonos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CodArea,Numero,Principal,Tipo,PersonaId")] Telefono telefono)
        {
            if (id != telefono.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(telefono);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TelefonoExists(telefono.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PersonaId"] = new SelectList(_context.Personas, "Id", "Apellido", telefono.PersonaId);
            return View(telefono);
        }

        // GET: Telefonos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telefono = await _context.Telefono
                .Include(t => t.Persona)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (telefono == null)
            {
                return NotFound();
            }

            return View(telefono);
        }

        // POST: Telefonos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var telefono = await _context.Telefono.FindAsync(id);
            if (telefono != null)
            {
                _context.Telefono.Remove(telefono);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TelefonoExists(int id)
        {
            return _context.Telefono.Any(e => e.Id == id);
        }
    }
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Personas/Create.cshtml
@model _2024__1C_Estacionamiento.Models.Persona

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Persona</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dni" class="control-label"></label>
                <input asp-for="Dni" class="form-control" />
                <span asp-validation-for="Dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Personas/Delete.cshtml
@model _2024__1C_Estacionamiento.Models.Persona

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Personas/Details.cshtml
@model _2024__1C_Estacionamiento.Models.Persona

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <h4>@Html.DisplayNameFor(Model => Model.Direccion)</h4>
    @if (Model.Direccion != null)
    {
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Direccion.Calle)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Direccion.Calle)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Direccion.Numero)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Direccion.Numero)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Direccion.CodPostal)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Direccion.CodPostal)
            </dd>

        </dl>
    }
    else
    {
        <h6>No hay dirección registrada</h6>
    }
</div>
<div>

    @if (Model.Telefonos != null && Model.Telefonos.Count != 0)
    {
        <h4>@Html.DisplayNameFor(Model => Model.Telefonos)</h4>

        foreach (Telefono telefono in Model.Telefonos)
        {
            <p>@telefono.NumeroCompleto</p>


        }

    }
    else
    {
        <h6>No hay Telefonos registrados</h6>
        <a asp-action="Create" asp-controller="Telefonos" class="btn btn-sm btn-info">Agregar Telefono</a>
    }
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Personas/Edit.cshtml
@model _2024__1C_Estacionamiento.Models.Persona

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Persona</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dni" class="control-label"></label>
                <input asp-for="Dni" class="form-control" />
                <span asp-validation-for="Dni" class="text-danger"></span>
            </div>

            
             <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
                
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

2024--1C-Estacionamiento/2024--1C-Estacionamiento/Views/Personas/Index.cshtml
@model IEnumerable<Persona>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>